#+OPTIONS:  ^:nil
#+TITLE: Customization
#+DESCRIPTION:
#+KEYWORDS:
#+STARTUP:  overview
#+DATE: 2020-05-04
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://gongzhitaao.org/orgcss/org.css"/>

~org-glaux~ can be customized under the group ~tools/org-glaux~. 

* General settings
- List of org-glaux root directories.
#+begin_src emacs-lisp 
(setq org-glaux-location-list '("~/org/wiki")
#+end_src

- If this variable is non-nil all org-glaux pages will be read-only by default. 
#+begin_src emacs-lisp
(setq org-glaux-default-read-only nil)
#+end_src

- If set, all org-glaux pages are closed when root directory is switched.
#+begin_src emacs-lisp 
(setq org-glaux-close-root-switch t)
#+end_src

Default template used to create org-glaux pages/files.
- %n - is replaced by the page name.
- %d - is replaced by current date in the format year-month-day.
#+begin_src emacs-lisp 
(setq org-glaux-template
  (string-trim
   "
#+OPTIONS: d:nil tags:nil todo:nil toc:t ^:nil
#+TITLE: %n
#+DESCRIPTION:
#+KEYWORDS:
#+STARTUP:  overview
#+DATE: %d
#+BIBLIOGRAPHY: main plain
")
#+end_src

- Default index page (index.org) accessed with ~M-x org-glaux-index~
#+begin_src emacs-lisp 
(defvar org-glaux-index-file-basename "index")
#+end_src

* Version control settings

- Activate edit history using version control software (VCS)
  - ~'git~: for git support
  - ~nil~: no version control
#+begin_src emacs-lisp 
(setq org-glaux-vc-backend 'git)
#+end_src

- Do not register file having size exceeding an amount of bytes.
#+begin_src emacs-lisp 
(setq org-glaux-vc-ignore-files-exceed-size (* 150 1024 1024))
#+end_src


-  List of glob patterns to exclude directories from version control.
These ignored-patterns apply on every wiki and have effect only if
`org-glaux-vc-wiki-pages-only' is nil.  To specify a per-wiki or
per-directory files pattern to ignore, include them in a local `.gitignore'
instead.

#+begin_src emacs-lisp 
(setq org-glaux-vc-ignored-dirs-glob
  (append '("*ltximg*" "*_minted*")
	  (mapcar (lambda (d) (format "*%s*" d)) vc-directory-exclusion-list)))
#+end_src

- These ignored-patterns apply on every wiki and have effect only if
`org-glaux-vc-wiki-pages-only' is nil.  To specify a per-wiki or
per-directory files pattern to ignore, include them in a local `.gitignore'
instead. List of glob patterns to exclude file-path from version control.

#+begin_src emacs-lisp 
(setq org-glaux-vc-ignored-files-glob '("*.html" "*.bbl" "*.tex" "*~" "*#*?#")
#+end_src

- If non-nil, the version control applies only on wiki pages (.org files).
#+begin_src emacs-lisp :tangle yes
(setq org-glaux-vc-wiki-pages-only nil)
#+end_src

- "Indicate when files are registered in version control and committed."
  - ~'close~ : commit opened wiki buffers when `org-glaux-close-pages' is called
  - ~'follow~ : commit when follow a wiki page
  - ~'manual~ : always commit manually
  
#+begin_src emacs-lisp 
(setq org-glaux-vc-commit-when 'close)
#+end_src

* Python webserver settings
  
- Default port to server org-glaux static files server. 
#+begin_src emacs-lisp :tangle yes
(setq org-glaux-server-port "8000")
#+end_src

- Default address that the server listens to.
#+begin_src emacs-lisp 
(setq org-glaux-server-host "0.0.0.0")
#+end_src

* Async export settings
  
- Additional options passed to `org-publish'.
#+begin_src emacs-lisp
(setq org-glaux-publish-plist '())
#+end_src

* Backup settings

- Path to backup directory.
#+begin_src emacs-lisp 
(setq org-glaux-backup-location nil)
#+end_src
