#+TITLE: Org-glaux 
Glaux (/[[https://en.wiktionary.org/wiki/%CE%B3%CE%BB%CE%B1%E1%BF%A6%CE%BE#Ancient_Greek][γλαῦξ]]/) is a personal wiki using the wiseness of org-mode.

** Features
- Support backward navigation (~org-glaux-navi-back~).
- Support sub-directories.
- Support dead wiki link highlighting.
- Support edit history (with ~git~ + automatic commit).
- and more...
** Installation
   
Before this package get into MELPA, there are two alternatives to install
~org-glaux~ : manually or with ~quelpa-use-package~. The recommended
configuration can be found below.

*** Manual
  
- ~git clone https://github.com/firmart/git-glaux ~/.emacs.d/lisp/git-glaux~
   

#+begin_src emacs-lisp
(use-package org-glaux
    :pin manual
    :load-path "lisp/org-glaux/"
    :bind ("C-c w" . org-glaux-index)
    :config 
    ;; Wikis location. default: '("~/org/wiki")
    (setq org-glaux-location-list '("~/Org/wiki" "~/Org/wiki2")) 
    ;; Destination to generate backup. default: nil
    (setq org-glaux-backup-location "~/Org/wiki/index/")
    ;; Enable org-glaux menu. Optional.
    (org-glaux-menu-enable))
#+end_src

*** ~quelpa-use-package~
    
- ~M-x package-install RET quelpa-use-package RET~
- Make sure you have ~(require 'quelpa)~ and ~(require 'quelpa-use-package)~ 
  somewhere in your configuration (or equivalently with ~use-package~).
    
#+begin_src emacs-lisp
(use-package org-glaux
  :quelpa (org-glaux :repo "firmart/org-glaux" :fetcher github)
  :config
  ;; Wikis location. default: '("~/org/wiki")
  (setq org-glaux-location-list '("~/Org/wiki" "~/Org/wiki2")) 
  ;; Destination to generate backup. default: nil
  (setq org-glaux-backup-location "~/Org/wiki/index/")
  ;; Enable org-glaux menu. Optional.
  (org-glaux-menu-enable)) 
#+end_src

** Link formats
   Wiki-links are in [[https://en.wikipedia.org/wiki/Help:Link#Subpage_links][Wikipedia-style]].

  |---------------------------+----------------------------------------------------------|
  | Link                      | To                                                       |
  |---------------------------+----------------------------------------------------------|
  | ~wiki:path/to/<pagename>~ | Absolute path: ~<org-glaux-location>/path/to/<pagename>~ |
  | ~wiki:/<pagename>~        | Child page: ~<current_page>/<pagename>~                  |
  | ~wiki:../~                | Parent page                                              |
  | ~wiki:../<pagename>~      | Sibling page                                             |
  |---------------------------+----------------------------------------------------------|

** Wishlist
 - Support showing page description on point
 - Support image gallery
** Credits
~org-glaux~ is based upon [[https://github.com/caiorss/org-wiki/issues][org-wiki]] of Caio Rodrigues.
